INFERANALYZE= /usr/local/Cellar/infer/0.8.1/libexec/infer/lib/python/inferlib/../../../bin/InferAnalyze $(INFER_OPTIONS) -results_dir '/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out'

CLUSTERS=cl1 cl2 cl3 cl4 cl5 cl6 cl7 cl8 cl9 cl10 cl11 cl12 cl13 cl14 cl15 cl16 cl17 cl18 cl19 cl20 cl21 cl22 cl23 cl24 cl25 cl26 cl27 cl28 cl29 cl30 cl31 cl32 cl33 cl34 cl35 cl36 cl37 cl38 cl39 cl40 cl41 cl42 cl43 cl44 cl45 cl46 cl47 cl48 cl49 cl50 cl51 cl52 cl53 cl54 cl55 cl56 cl57 cl58 cl59 cl60 cl61 cl62 cl63 cl64 cl65 cl66 cl67 cl68 cl69 cl70 cl71 cl72 cl73 cl74 cl75 cl76 cl77 cl78 cl79 cl80 cl81 cl82 cl83 cl84 cl85 cl86 cl87 cl88 cl89 cl90 cl91 cl92 cl93 cl94 cl95 cl96 cl97 cl98 cl99 cl100 cl101 cl102 cl103 cl104 cl105 cl106 cl107 cl108 cl109 cl110 cl111 cl112 cl113 cl114 cl115 cl116 cl117 cl118 cl119 cl120 cl121 cl122 cl123 cl124 cl125 cl126 cl127 cl128 cl129 cl130 cl131 cl132 cl133 cl134 cl135 cl136 cl137 cl138 cl139 cl140 cl141 cl142 cl143 cl144 cl145 cl146 cl147 cl148 cl149 cl150 cl151 cl152 cl153 cl154 cl155 cl156 cl157 cl158 cl159 cl160 cl161 cl162 cl163 cl164 cl165 cl166 cl167 cl168 cl169 cl170 cl171 cl172 

default: test

all: test

test: $(CLUSTERS)
	echo ""
#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ActivityComponent.java.9193b68455e6fd720c0151bae474a35d
cl1: 
	$(INFERANALYZE) -cluster xcl1.cluster >cl1

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ActivityModule.java.8f28c590f9f006c80af35c2f2d45d134
cl2: 
	$(INFERANALYZE) -cluster xcl2.cluster >cl2

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ActivityModule_ActivityFactory.java.c6ad08377bf46a23c0a6673f7f922a7e
cl3: 
	$(INFERANALYZE) -cluster xcl3.cluster >cl3

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ActivityModule_ActivityFactory.java.ec1c62f26795dc142f96767ca1114b23
cl4: 
	$(INFERANALYZE) -cluster xcl4.cluster >cl4

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ActivityModule_ProvidesGetGeneralListUseCaseFactory.java.43df61510947197fe9fed7e18b6cb64d
cl5: 
	$(INFERANALYZE) -cluster xcl5.cluster >cl5

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ActivityModule_ProvidesGetGeneralListUseCaseFactory.java.60cbf12799206c0e6344cc7b6f826487
cl6: 
	$(INFERANALYZE) -cluster xcl6.cluster >cl6

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ActivityModule_ProvidesNavigatorFactory.java.a58b67d1f1eabef8ed3e274d0684b61d
cl7: 
	$(INFERANALYZE) -cluster xcl7.cluster >cl7

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ActivityModule_ProvidesNavigatorFactory.java.f656d79e3bfb3fd7a829739600a36ebe
cl8: 
	$(INFERANALYZE) -cluster xcl8.cluster >cl8

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/AndroidApplication.java.81097c40f0ac963e1b23850baf9880d7
cl9: 
	$(INFERANALYZE) -cluster xcl9.cluster >cl9

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApiConnection.java.742c19d0f8a46fcebc5ff48d713e93f0
cl10: 
	$(INFERANALYZE) -cluster xcl10.cluster >cl10

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationComponent.java.acdc745d6ad8c9406376c2e8f1f3ac3b
cl11: 
	$(INFERANALYZE) -cluster xcl11.cluster >cl11

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule.java.1fdbfba72658d59a7f704215f511e533
cl12: 
	$(INFERANALYZE) -cluster xcl12.cluster >cl12

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideApplicationContextFactory.java.0d0881fbd327a35d7301415f92d594a4
cl13: 
	$(INFERANALYZE) -cluster xcl13.cluster >cl13

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideApplicationContextFactory.java.9fffa81344c2733cb390f2ec8793ef92
cl14: 
	$(INFERANALYZE) -cluster xcl14.cluster >cl14

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideGeneralRealmManagerFactory.java.18c1f8dbde94c3a00ce4e4621de532a1
cl15: 
	$(INFERANALYZE) -cluster xcl15.cluster >cl15

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideGeneralRealmManagerFactory.java.9a482b2d09559613418e3281f324624c
cl16: 
	$(INFERANALYZE) -cluster xcl16.cluster >cl16

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideGsonFactory.java.3c8dab9db236e317ad4b80d9742884ac
cl17: 
	$(INFERANALYZE) -cluster xcl17.cluster >cl17

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideGsonFactory.java.b31b07ea702337778c47f50a3bf206a4
cl18: 
	$(INFERANALYZE) -cluster xcl18.cluster >cl18

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvidePostExecutionThreadFactory.java.6fd581e05126920753bf52356436293f
cl19: 
	$(INFERANALYZE) -cluster xcl19.cluster >cl19

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvidePostExecutionThreadFactory.java.e140dc6a90d5845df731f64564efa4fd
cl20: 
	$(INFERANALYZE) -cluster xcl20.cluster >cl20

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideRepositoryFactory.java.39710ca102f4655bb09525091fe9dbf4
cl21: 
	$(INFERANALYZE) -cluster xcl21.cluster >cl21

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideRepositoryFactory.java.c1998a8402c15d6f7e169c1c944cf94c
cl22: 
	$(INFERANALYZE) -cluster xcl22.cluster >cl22

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideRxEventBusFactory.java.8bbf954f6affaea81d2c24a6b9e90496
cl23: 
	$(INFERANALYZE) -cluster xcl23.cluster >cl23

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideRxEventBusFactory.java.96f9d05835b02369d48dbd106c38fb17
cl24: 
	$(INFERANALYZE) -cluster xcl24.cluster >cl24

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideThreadExecutorFactory.java.2f7e7176400d94f23d0dce7877973bdb
cl25: 
	$(INFERANALYZE) -cluster xcl25.cluster >cl25

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ApplicationModule_ProvideThreadExecutorFactory.java.76e2e6f358f813b2b2b3942075c0bb57
cl26: 
	$(INFERANALYZE) -cluster xcl26.cluster >cl26

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/AutoLoadImageView.java.b589917bbe1b32dfd604784b9849c9af
cl27: 
	$(INFERANALYZE) -cluster xcl27.cluster >cl27

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/BaseActivity.java.269cc070eb0c5124a90bd596b8719c47
cl28: 
	$(INFERANALYZE) -cluster xcl28.cluster >cl28

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/BaseActivity_MembersInjector.java.96f8ca5846bb4cc549bcf552e5971472
cl29: 
	$(INFERANALYZE) -cluster xcl29.cluster >cl29

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/BaseActivity_MembersInjector.java.a8de77ef285dc205dbc0ff3093117170
cl30: 
	$(INFERANALYZE) -cluster xcl30.cluster >cl30

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/BaseFragment.java.2a58f75286b6a48fa50611db63a66af5
cl31: 
	$(INFERANALYZE) -cluster xcl31.cluster >cl31

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/BasePresenter.java.0c2578a74f685f4704c2b773f242e206
cl32: 
	$(INFERANALYZE) -cluster xcl32.cluster >cl32

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/BaseUseCase.java.d648ca7bedfc0fd99d874e0b73d9f842
cl33: 
	$(INFERANALYZE) -cluster xcl33.cluster >cl33

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/BuildConfig.java.d75edc0daa3f11a217ea6fac3a21a536
cl34: 
	$(INFERANALYZE) -cluster xcl34.cluster >cl34

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/BuildConfig.java.e54c768cacca45c3572b6e1ead05cbfb
cl35: 
	$(INFERANALYZE) -cluster xcl35.cluster >cl35

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/CloudDataStore.java.6e8012fe4f8f09074c0088246760baef
cl36: 
	$(INFERANALYZE) -cluster xcl36.cluster >cl36

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/Constants.java.ec9f3325c2a090cf16f1ede9143e5474
cl37: 
	$(INFERANALYZE) -cluster xcl37.cluster >cl37

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DaggerActivityComponent.java.2462b1ac5d2bbf68efe2041834f0d655
cl38: 
	$(INFERANALYZE) -cluster xcl38.cluster >cl38

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DaggerActivityComponent.java.b483207406a41a8deb09330c89c593c3
cl39: 
	$(INFERANALYZE) -cluster xcl39.cluster >cl39

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DaggerApplicationComponent.java.489bcccb65b95596d81566d4abcd7199
cl40: 
	$(INFERANALYZE) -cluster xcl40.cluster >cl40

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DaggerApplicationComponent.java.aed35a4dccf11afccfe6e1699737357f
cl41: 
	$(INFERANALYZE) -cluster xcl41.cluster >cl41

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DaggerUserComponent.java.5e3d9dd61887fd03cf40d87c14d59503
cl42: 
	$(INFERANALYZE) -cluster xcl42.cluster >cl42

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DaggerUserComponent.java.86f786dd47cf8158685600c8ee4b7490
cl43: 
	$(INFERANALYZE) -cluster xcl43.cluster >cl43

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DataRepository.java.81d3a8e4288dd07f524fa354f8fe722b
cl44: 
	$(INFERANALYZE) -cluster xcl44.cluster >cl44

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DataRepository_Factory.java.3e74daf3f497644a1f4b5a58d3bfa508
cl45: 
	$(INFERANALYZE) -cluster xcl45.cluster >cl45

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DataRepository_Factory.java.89bbf9223b33733e8d941454c74b71f2
cl46: 
	$(INFERANALYZE) -cluster xcl46.cluster >cl46

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DataStore.java.2eec39a22ada7d149f406adac808a1d6
cl47: 
	$(INFERANALYZE) -cluster xcl47.cluster >cl47

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DataStoreFactory.java.2ba5b369a9010b0da4bf1ac9f38c1e8f
cl48: 
	$(INFERANALYZE) -cluster xcl48.cluster >cl48

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DataStoreFactory_Factory.java.8b257c7d204ad48c5fc9bfcb8a99ff4f
cl49: 
	$(INFERANALYZE) -cluster xcl49.cluster >cl49

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DataStoreFactory_Factory.java.a15bdbc5453cddf553af07a917a072ac
cl50: 
	$(INFERANALYZE) -cluster xcl50.cluster >cl50

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DefaultErrorBundle.java.b3daa35235ec18c24c08d617c4551f07
cl51: 
	$(INFERANALYZE) -cluster xcl51.cluster >cl51

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DefaultRealmModule.java.a69522c84b4d4387fcc9e2799e7c5b60
cl52: 
	$(INFERANALYZE) -cluster xcl52.cluster >cl52

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DefaultRealmModule.java.cf90b23dfe2d353ccbbec47333a55313
cl53: 
	$(INFERANALYZE) -cluster xcl53.cluster >cl53

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DefaultRealmModuleMediator.java.8781a60252fea32c9c82895d7f2c93e1
cl54: 
	$(INFERANALYZE) -cluster xcl54.cluster >cl54

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DefaultRealmModuleMediator.java.be90e3d81461d7bbda946d491b0ba0dc
cl55: 
	$(INFERANALYZE) -cluster xcl55.cluster >cl55

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DefaultSubscriber.java.92bf4785681aa6863cf2b74307dce82d
cl56: 
	$(INFERANALYZE) -cluster xcl56.cluster >cl56

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/Delete.java.15cf3f49d7cbf1ea0f2a55f0a7cf2743
cl57: 
	$(INFERANALYZE) -cluster xcl57.cluster >cl57

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DetailsTransition.java.7e595af6d380a2f43459e3672633b379
cl58: 
	$(INFERANALYZE) -cluster xcl58.cluster >cl58

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DiskDataStore.java.ae09c96047b2b2f2211a02b77e86f4c4
cl59: 
	$(INFERANALYZE) -cluster xcl59.cluster >cl59

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/DownloadImage.java.e0f1f8b2f49dc1e3d32fc915a5e9deef
cl60: 
	$(INFERANALYZE) -cluster xcl60.cluster >cl60

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/EntityMapper.java.07fb413cc712cc4cfdbf53d42465ff72
cl61: 
	$(INFERANALYZE) -cluster xcl61.cluster >cl61

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ErrorBundle.java.6a067135daaa8047f988085d9db530cc
cl62: 
	$(INFERANALYZE) -cluster xcl62.cluster >cl62

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ErrorMessageFactory.java.3ef2db914e32bc3405936653b10c9814
cl63: 
	$(INFERANALYZE) -cluster xcl63.cluster >cl63

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GeneralRealmManager.java.d4b95678ad4dddbb6541e679d62b09dc
cl64: 
	$(INFERANALYZE) -cluster xcl64.cluster >cl64

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GeneralRealmManagerImpl.java.0b72350d9b82576aec158844f5c67cc4
cl65: 
	$(INFERANALYZE) -cluster xcl65.cluster >cl65

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GeneralRealmManagerImpl_Factory.java.5310eddd83c0259d0ce67814e07fb3bb
cl66: 
	$(INFERANALYZE) -cluster xcl66.cluster >cl66

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GeneralRealmManagerImpl_Factory.java.64b609ec5134ca04af4f7956ee77f840
cl67: 
	$(INFERANALYZE) -cluster xcl67.cluster >cl67

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericDetailPresenter.java.f43f05c1d5a6979740b56510a348d7ef
cl68: 
	$(INFERANALYZE) -cluster xcl68.cluster >cl68

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericDetailView.java.83f19acf558177ea4efaf8b063021305
cl69: 
	$(INFERANALYZE) -cluster xcl69.cluster >cl69

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericEditableItemView.java.0f064b9e97309401a266018c6dc2145f
cl70: 
	$(INFERANALYZE) -cluster xcl70.cluster >cl70

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericExtendedDetailPresenter.java.7b3b3605947c3a066005d73a2f27e522
cl71: 
	$(INFERANALYZE) -cluster xcl71.cluster >cl71

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericGCMService.java.02a25801fc23ac1ae8cea852e4127bd7
cl72: 
	$(INFERANALYZE) -cluster xcl72.cluster >cl72

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericJobService.java.a12de1e84daeda7901255d811ba34850
cl73: 
	$(INFERANALYZE) -cluster xcl73.cluster >cl73

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericListExtendedPresenter.java.c93b7a02eb5fa0ec1bbe3375ad104d1f
cl74: 
	$(INFERANALYZE) -cluster xcl74.cluster >cl74

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericListPresenter.java.54145089d14379b695335309b76d9604
cl75: 
	$(INFERANALYZE) -cluster xcl75.cluster >cl75

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericListView.java.4c4689f2a88cda842c20c8eaf44e1793
cl76: 
	$(INFERANALYZE) -cluster xcl76.cluster >cl76

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericNetworkQueueIntentService.java.b11723182f1a7fb6bae8b13e29399de1
cl77: 
	$(INFERANALYZE) -cluster xcl77.cluster >cl77

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericNetworkQueueIntentService_MembersInjector.java.27833a54dc91715b90a60cee9cf5fb34
cl78: 
	$(INFERANALYZE) -cluster xcl78.cluster >cl78

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericNetworkQueueIntentService_MembersInjector.java.6c4327cdce8fe5283ff2d80110c5af35
cl79: 
	$(INFERANALYZE) -cluster xcl79.cluster >cl79

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericRecyclerViewAdapter.java.b659316c9b8b6e8c77adfb483c51e184
cl80: 
	$(INFERANALYZE) -cluster xcl80.cluster >cl80

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericUseCase.java.305624c449c92570d9550701881d7950
cl81: 
	$(INFERANALYZE) -cluster xcl81.cluster >cl81

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericUseCase_Factory.java.2fc2079b226450e26aa1a3ce1337f386
cl82: 
	$(INFERANALYZE) -cluster xcl82.cluster >cl82

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/GenericUseCase_Factory.java.b326df900efd4d9cb26c0054deecf273
cl83: 
	$(INFERANALYZE) -cluster xcl83.cluster >cl83

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/HasComponent.java.a3c83c222813772e7f674426a44674e5
cl84: 
	$(INFERANALYZE) -cluster xcl84.cluster >cl84

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ItemBase.java.8d87e2d022e2a4e3576daab420d999e1
cl85: 
	$(INFERANALYZE) -cluster xcl85.cluster >cl85

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ItemInfo.java.97de72a15954e065707bfdacc25f0ab4
cl86: 
	$(INFERANALYZE) -cluster xcl86.cluster >cl86

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/JobExecutor.java.6f5600f2d95f1e78e4232528945aaae4
cl87: 
	$(INFERANALYZE) -cluster xcl87.cluster >cl87

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/JobExecutor_Factory.java.03a7f178b0a8e3c127dd1b4743bd1448
cl88: 
	$(INFERANALYZE) -cluster xcl88.cluster >cl88

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/JobExecutor_Factory.java.21008c13a8e669286289a32fd5608b58
cl89: 
	$(INFERANALYZE) -cluster xcl89.cluster >cl89

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/LoadDataView.java.160cb9c17122abd4d772fc1578b9eda2
cl90: 
	$(INFERANALYZE) -cluster xcl90.cluster >cl90

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/MainActivity$$ViewBinder.java.0cb5407c7ce702ca3b5c92dca65be220
cl91: 
	$(INFERANALYZE) -cluster xcl91.cluster >cl91

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/MainActivity$$ViewBinder.java.16577491b3374b2fd3ae92897aec4ea3
cl92: 
	$(INFERANALYZE) -cluster xcl92.cluster >cl92

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/MainActivity.java.7f56148082fbc066d573539632ee0ef1
cl93: 
	$(INFERANALYZE) -cluster xcl93.cluster >cl93

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ModelDataMapper.java.e161946a613e98666b045f97a680fdee
cl94: 
	$(INFERANALYZE) -cluster xcl94.cluster >cl94

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ModelDataMapper_Factory.java.431da385eb1dbce624a5636f7a21640b
cl95: 
	$(INFERANALYZE) -cluster xcl95.cluster >cl95

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ModelDataMapper_Factory.java.615629ecf5d4a5cb7117db3d39932fa6
cl96: 
	$(INFERANALYZE) -cluster xcl96.cluster >cl96

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/Navigator.java.983fd507d8f751f952db0ef06914d77f
cl97: 
	$(INFERANALYZE) -cluster xcl97.cluster >cl97

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/NetworkChangeReceiver.java.1787205185b88ffde05d28edc5458892
cl98: 
	$(INFERANALYZE) -cluster xcl98.cluster >cl98

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/NetworkConnectionException.java.4c7041fdbe1435534ea8ca8750e483b7
cl99: 
	$(INFERANALYZE) -cluster xcl99.cluster >cl99

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/PerActivity.java.d669060f3ed7dd84ac2391bc7da6885a
cl100: 
	$(INFERANALYZE) -cluster xcl100.cluster >cl100

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/Post.java.aa561a76d54ba59eb5e828b7acb2bc3f
cl101: 
	$(INFERANALYZE) -cluster xcl101.cluster >cl101

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/PostExecutionThread.java.6dbb628d974089fd4c4f5701e47808a1
cl102: 
	$(INFERANALYZE) -cluster xcl102.cluster >cl102

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.101997002e344a7953618314596fe733
cl103: 
	$(INFERANALYZE) -cluster xcl103.cluster >cl103

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.21f2d72126b640418e8c48ff9f86ed7d
cl104: 
	$(INFERANALYZE) -cluster xcl104.cluster >cl104

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.3af832ea846dbd7486f6cfcba6b6c4ad
cl105: 
	$(INFERANALYZE) -cluster xcl105.cluster >cl105

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.4d6b9cece30f1cb3978e3b3a891aa7b4
cl106: 
	$(INFERANALYZE) -cluster xcl106.cluster >cl106

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.5432418f97e6aeb8d2fc10ff2a64962d
cl107: 
	$(INFERANALYZE) -cluster xcl107.cluster >cl107

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.99ffd166a8154b5ba690dc0366a08c9b
cl108: 
	$(INFERANALYZE) -cluster xcl108.cluster >cl108

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.c471907e3b911762a18081d49986896d
cl109: 
	$(INFERANALYZE) -cluster xcl109.cluster >cl109

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.c529c38fc784ac45ae8186e4ce15bc17
cl110: 
	$(INFERANALYZE) -cluster xcl110.cluster >cl110

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.c94c2e5c9a88d638c61f3916e98e3398
cl111: 
	$(INFERANALYZE) -cluster xcl111.cluster >cl111

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.cf51053e546982aee841b3b230307608
cl112: 
	$(INFERANALYZE) -cluster xcl112.cluster >cl112

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.df61757eb2f060bec9f65ab9040c6284
cl113: 
	$(INFERANALYZE) -cluster xcl113.cluster >cl113

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.e6763d2f3165247af24a0459cabf72a8
cl114: 
	$(INFERANALYZE) -cluster xcl114.cluster >cl114

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.e81359d13ced8908235a70757a577518
cl115: 
	$(INFERANALYZE) -cluster xcl115.cluster >cl115

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.ed2872b26942afa5a8f13a8f68c107c1
cl116: 
	$(INFERANALYZE) -cluster xcl116.cluster >cl116

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/R.java.ee59d3b9df4550d0f3db3da9b2fbf1b8
cl117: 
	$(INFERANALYZE) -cluster xcl117.cluster >cl117

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/RecyclerViewHeadFootViewHolder$$ViewBinder.java.4e5d2641a083c4d7175ad7645218e271
cl118: 
	$(INFERANALYZE) -cluster xcl118.cluster >cl118

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/RecyclerViewHeadFootViewHolder$$ViewBinder.java.806de0bbd633bcb5144d9e329f1292c6
cl119: 
	$(INFERANALYZE) -cluster xcl119.cluster >cl119

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/RecyclerViewHeadFootViewHolder.java.8ebf4bad489128f620b680a2ac80024f
cl120: 
	$(INFERANALYZE) -cluster xcl120.cluster >cl120

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/RecyclerViewLoadingViewHolder.java.51c760d91b356d5ca7a2d98f9d098efb
cl121: 
	$(INFERANALYZE) -cluster xcl121.cluster >cl121

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/Repository.java.e9f5d4413313908ec25cba7c9a4e5286
cl122: 
	$(INFERANALYZE) -cluster xcl122.cluster >cl122

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/RepositoryErrorBundle.java.04f68569ec20bd87957d1a8c661a5342
cl123: 
	$(INFERANALYZE) -cluster xcl123.cluster >cl123

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/RestApi.java.49befb023d0494ed87bfb606e5be5d80
cl124: 
	$(INFERANALYZE) -cluster xcl124.cluster >cl124

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/RestApiImpl.java.a0ca1f8776dfb6b60c79f9a47c1eca0e
cl125: 
	$(INFERANALYZE) -cluster xcl125.cluster >cl125

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/RxEventBus.java.59407a60517b55162565ab0066830cca
cl126: 
	$(INFERANALYZE) -cluster xcl126.cluster >cl126

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/ThreadExecutor.java.fb73801d0a6bafe7d266f6817a83025d
cl127: 
	$(INFERANALYZE) -cluster xcl127.cluster >cl127

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UIThread.java.f3afcc2a7fda6d39771dc66044a266ae
cl128: 
	$(INFERANALYZE) -cluster xcl128.cluster >cl128

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UIThread_Factory.java.2d9e9384f70d387239e7f5839144fce4
cl129: 
	$(INFERANALYZE) -cluster xcl129.cluster >cl129

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UIThread_Factory.java.9fd815fa23a7614d6b1ab7cff657105a
cl130: 
	$(INFERANALYZE) -cluster xcl130.cluster >cl130

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UploadImage.java.4fb922f00f8710820d3a852691a69342
cl131: 
	$(INFERANALYZE) -cluster xcl131.cluster >cl131

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/User.java.8cfb48dad390bc7ec39af02b5713c3da
cl132: 
	$(INFERANALYZE) -cluster xcl132.cluster >cl132

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserComponent.java.f7d721ea458e110f9befcacd8633b13d
cl133: 
	$(INFERANALYZE) -cluster xcl133.cluster >cl133

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailPresenter.java.1c4dc6e12cd6e3ede9989497420424c4
cl134: 
	$(INFERANALYZE) -cluster xcl134.cluster >cl134

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailPresenter_Factory.java.5c94cc37fa00f31e49aaf250727d5466
cl135: 
	$(INFERANALYZE) -cluster xcl135.cluster >cl135

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailPresenter_Factory.java.d7090e03f458b3d24e86176e57086952
cl136: 
	$(INFERANALYZE) -cluster xcl136.cluster >cl136

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailsActivity$$ViewBinder.java.4738c9a3a67771cc219290541a8aeaa3
cl137: 
	$(INFERANALYZE) -cluster xcl137.cluster >cl137

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailsActivity$$ViewBinder.java.f9ce28784e6d640443d7a27383b55ac6
cl138: 
	$(INFERANALYZE) -cluster xcl138.cluster >cl138

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailsActivity.java.a19e5223ab333feb87947824ba5ed1e5
cl139: 
	$(INFERANALYZE) -cluster xcl139.cluster >cl139

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailsFragment$$ViewBinder.java.a60aedc4a2cc060257eea9e0e7ee01c5
cl140: 
	$(INFERANALYZE) -cluster xcl140.cluster >cl140

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailsFragment$$ViewBinder.java.bfcb5b2876ab3e9258006d2a8ff36750
cl141: 
	$(INFERANALYZE) -cluster xcl141.cluster >cl141

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailsFragment.java.5d419bdebe3ac945e6e5ccc936d5af3c
cl142: 
	$(INFERANALYZE) -cluster xcl142.cluster >cl142

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailsFragment_MembersInjector.java.3c2b3904e5888c4c59f06fe081b00060
cl143: 
	$(INFERANALYZE) -cluster xcl143.cluster >cl143

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserDetailsFragment_MembersInjector.java.536b6b3f6757e4deef25e483a7eebf58
cl144: 
	$(INFERANALYZE) -cluster xcl144.cluster >cl144

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserEntityDataMapper.java.03de51481b55e05713986e9cf5f65649
cl145: 
	$(INFERANALYZE) -cluster xcl145.cluster >cl145

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserEntityDataMapper_Factory.java.3fe17a09d450b28826ecd9788b13974e
cl146: 
	$(INFERANALYZE) -cluster xcl146.cluster >cl146

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserEntityDataMapper_Factory.java.6e5ccfa8ddf341ea80ca4de5e80424f9
cl147: 
	$(INFERANALYZE) -cluster xcl147.cluster >cl147

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserListActivity$$ViewBinder.java.80c3b365ec2f137117c23274afcd8a9f
cl148: 
	$(INFERANALYZE) -cluster xcl148.cluster >cl148

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserListActivity$$ViewBinder.java.c2096471dfc0d83c29ccc047dda77802
cl149: 
	$(INFERANALYZE) -cluster xcl149.cluster >cl149

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserListActivity.java.a2d8c9d623bbbacae2dea53de05cc3d2
cl150: 
	$(INFERANALYZE) -cluster xcl150.cluster >cl150

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserListActivity_MembersInjector.java.6fc8c91936c8897e73fc5b00f06f32f6
cl151: 
	$(INFERANALYZE) -cluster xcl151.cluster >cl151

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserListActivity_MembersInjector.java.c49032a3b628cc919876493aecc688fb
cl152: 
	$(INFERANALYZE) -cluster xcl152.cluster >cl152

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserListPresenter.java.17fa66dc52db5deba859aeb6373f952e
cl153: 
	$(INFERANALYZE) -cluster xcl153.cluster >cl153

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserListPresenter_Factory.java.3677b37b76b34d203794f554b18235c8
cl154: 
	$(INFERANALYZE) -cluster xcl154.cluster >cl154

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserListPresenter_Factory.java.85c0032b75763d61f86eebf6f435e4f1
cl155: 
	$(INFERANALYZE) -cluster xcl155.cluster >cl155

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserModule.java.3106a528a551eade000e24f3d6c73a79
cl156: 
	$(INFERANALYZE) -cluster xcl156.cluster >cl156

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserModule_ProvideGetGeneralListUseCaseFactory.java.659abd3572b1cc5be70718f027fad6d2
cl157: 
	$(INFERANALYZE) -cluster xcl157.cluster >cl157

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserModule_ProvideGetGeneralListUseCaseFactory.java.ab764ec48f85ef2df9dfe34b1a5e9207
cl158: 
	$(INFERANALYZE) -cluster xcl158.cluster >cl158

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserNotFoundException.java.5ada0d46444ed56cee2145c52c3212d2
cl159: 
	$(INFERANALYZE) -cluster xcl159.cluster >cl159

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserRealmModel.java.892d830e958779e1e3da2796be75fe66
cl160: 
	$(INFERANALYZE) -cluster xcl160.cluster >cl160

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserRealmModelRealmProxy.java.ced865f123b0cb439dff722383cf0d84
cl161: 
	$(INFERANALYZE) -cluster xcl161.cluster >cl161

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserRealmModelRealmProxy.java.d8cd593203cc3d55fd6f0fb3da739332
cl162: 
	$(INFERANALYZE) -cluster xcl162.cluster >cl162

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserRealmModelRealmProxyInterface.java.4f0f39e89e420be6836908728bb7f508
cl163: 
	$(INFERANALYZE) -cluster xcl163.cluster >cl163

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserRealmModelRealmProxyInterface.java.d90b2470d43ced268c778a7e933c59b7
cl164: 
	$(INFERANALYZE) -cluster xcl164.cluster >cl164

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserViewHolder$$ViewBinder.java.967b2ac587939bd9b7ad0224d6d1e25f
cl165: 
	$(INFERANALYZE) -cluster xcl165.cluster >cl165

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserViewHolder$$ViewBinder.java.b896749164c4fecea8c8262719ffb1d8
cl166: 
	$(INFERANALYZE) -cluster xcl166.cluster >cl166

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserViewHolder.java.03cc22d4b48bed18310931b92901ce30
cl167: 
	$(INFERANALYZE) -cluster xcl167.cluster >cl167

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserViewModel.java.b1f68ef84b9e3567456b1d937f4cf273
cl168: 
	$(INFERANALYZE) -cluster xcl168.cluster >cl168

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserViewModelDataMapper.java.70ced0a141c70e2f9c659ecd390b703c
cl169: 
	$(INFERANALYZE) -cluster xcl169.cluster >cl169

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserViewModelDataMapper_Factory.java.34adc7f9942eef33bff9e8b85567b242
cl170: 
	$(INFERANALYZE) -cluster xcl170.cluster >cl170

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/UserViewModelDataMapper_Factory.java.9fab136f277135813c6be751918a655c
cl171: 
	$(INFERANALYZE) -cluster xcl171.cluster >cl171

#/Users/ZIaDo/WorkSpaces/StudioProjects/CARlmRetro2RxTests/MyApplication/infer-out/captured/Utils.java.b7785238be29f63f396b7f5002ba0f37
cl172: 
	$(INFERANALYZE) -cluster xcl172.cluster >cl172


clean:
	rm -f $(CLUSTERS)
